version: '3'
services:
  api_1398:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "65043:65043"
    volumes:
      - .:/var/www/html
    depends_on:
      - db_1398
    env_file:
      - "./.env"
  db_1398:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=codifyer_database
      - MYSQL_DATABASE=db_1398
    volumes:
      - mysql-db-1398:/var/lib/mysql
    ports:
      - "62796:3306"
  phpmyadmin_1398:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_1398
    links:
      - db_1398
    environment:
      PMA_HOST: db_1398
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 64343:80

volumes:
  mysql-db-1398:
